blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/JefinFrancis/ct-b2c-storefront/discussions
    about: Ask questions or discuss ideas in GitHub Discussions
